#
# Copyright (c) 2022 Tommy Lau <http://tommy.net.cn/>
#
# https://github.com/TommyLau/actions-openwrt
# Description: Build OpenWrt image with GitHub Actions
#

name: Build FriendlyARM NanoPi R4S 4GB LPDDR4 Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/friendlyarm_nanopi-r4s.yml'
      - 'configs/r4s.config'
      - 'files/**'
      - 'scripts/**'

env:
  DEVICE_NAME: R4S
  PROFILE: friendlyarm_nanopi-r4s
  DEVICE_TARGET: rockchip
  DEVICE_SUB_TARGET: armv8
  CONFIG_FILE: configs/r4s.config
  OPENWRT_VERSION: 22.03.2
  OPENWRT_URL: "https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${DEVICE_TARGET}/${DEVICE_SUB_TARGET}"
  SDK_URL: "${OPENWRT_URL}/openwrt-sdk-${OPENWRT_VERSION}-${DEVICE_TARGET}-${DEVICE_SUB_TARGET}_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
  BUILDER_URL: "${OPENWRT_URL}/openwrt-imagebuilder-${OPENWRT_VERSION}-${DEVICE_TARGET}-${DEVICE_SUB_TARGET}.Linux-x86_64.tar.xz"
  TIMEZONE: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ./scripts/001-setup_build_environment.sh

    - name: Build Custom Packages
      run: |
        ./scripts/002-build_custom_packages.sh

    - name: Build Image
      run: |
        ./scripts/003-build_custom_image.sh

    - name: Space Usage
      if: (!cancelled())
      run: df -hT

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}
        path: |
          ${{ env.FIRMWARE_PATH }}/*.gz

    - name: Upload Packages
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt_${{ env.DEVICE_NAME }}_IPK_${{ env.BUILD_TIME }}
        path: builder/packages
