#
# Copyright (c) 2020-2024 Tommy Lau <https://tommy.net.cn/>
#
# https://github.com/TommyLau/actions-openwrt
# Description: Build OpenWrt image with GitHub Actions
#

name: Build Linksys E8450 UBI Image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/linksys_e8450-ubi.yml"
      - "configs/e8450.config"
      - "files/**"
      - "scripts/**"

env:
  DEVICE_NAME: E8450
  PROFILE: linksys_e8450-ubi
  DEVICE_TARGET: mediatek
  DEVICE_SUB_TARGET: mt7622

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          ./scripts/001-setup_build_environment.sh

      - name: Build Custom Packages
        run: |
          ./scripts/002-build_custom_packages.sh

      - name: Build Image
        run: |
          ./scripts/003-build_custom_image.sh

      - name: Space Usage
        if: (!cancelled())
        run: df -hT

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}
          path: |
            ${{ env.FIRMWARE_PATH }}/*.itb
            ${{ env.FIRMWARE_PATH }}/*.bin

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_${{ env.DEVICE_NAME }}_IPK_${{ env.BUILD_TIME }}
          path: builder/packages
